-- 000004_audit_outbox.up.sql
--
-- Phase 8: durable outbox pattern for audit events.
--
-- The architectural promise: a successful business mutation (task delete,
-- status change, etc.) implies a corresponding audit_log row exists. A
-- failed mutation implies no audit row exists. Both live or die together.
--
-- The mechanism: the service writes the audit event into THIS table —
-- audit_outbox — in the SAME database transaction as the business write.
-- Postgres makes that atomic. A background drainer goroutine
-- (internal/audit/drainer.go) reads from audit_outbox, INSERTs into
-- audit_log, DELETEs from audit_outbox, all inside its own transaction.
-- Crashes between those steps reprocess on the drainer's next iteration,
-- which is why the drain target (audit_log) has to be idempotent — and
-- it IS, because we reuse the outbox row's UUID as audit_log's primary
-- key. A duplicate drain is a primary-key conflict, which the drainer
-- treats as "already done, success".
--
-- Notes on the schema:
--
--   * id is generated by the application (not the database) so that the
--     same UUID can be used as audit_log.id when the drain inserts. This
--     is what makes the drain idempotent against the existing schema's
--     PK without any extra "already drained" tracking.
--
--   * claimed_at is an observability column, NOT a correctness mechanism.
--     The actual claim-and-skip logic is done via FOR UPDATE SKIP LOCKED
--     at SELECT time. claimed_at is updated before the audit_log insert
--     so operators investigating a stuck row can tell when a drainer
--     last touched it.
--
--   * detail JSONB matches audit_log exactly so the drain copy is a
--     straight column-for-column move with no transformation.
--
--   * No foreign keys. Option A persists: actor_sub is a Keycloak
--     subject, with no local users table to reference. Same as audit_log.

BEGIN;

CREATE TABLE audit_outbox (
    id          UUID PRIMARY KEY,
    enqueued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    claimed_at  TIMESTAMPTZ,                      -- nullable: NULL = not yet picked up
    actor_sub   UUID NOT NULL,
    action      TEXT NOT NULL CHECK (action <> ''),
    target_kind TEXT NOT NULL CHECK (target_kind <> ''),
    target_id   UUID NOT NULL,
    outcome     TEXT NOT NULL CHECK (outcome IN ('success', 'denied')),
    detail      JSONB,
    request_id  TEXT
);

-- The drainer queries unclaimed rows in enqueue order. Index covers that
-- exact pattern. We do NOT index claimed_at separately — the WHERE
-- always uses enqueued_at as the primary sort and claimed_at IS NULL as
-- the partial filter, which this partial index serves well.
CREATE INDEX audit_outbox_pending_idx
    ON audit_outbox(enqueued_at)
    WHERE claimed_at IS NULL;

COMMIT;
