// Package mocks contains testify/mock implementations of the repository
// interfaces.
//
// Normally these are GENERATED by `mockery` from the interface, not
// written by hand — that is the whole selling point of generated mocks.
// We hand-write this ONE so the course can show the contrast without
// adding a code-generation tool to the toolchain yet (mockery joins in a
// later phase if we want it). The structure here is exactly what
// `mockery --name=TaskRepository` would emit.
//
// Fake vs mock, the distinction this file exists to illustrate:
//
//   - A FAKE (service/fakes_test.go) really works. It stores and
//     retrieves. You assert on OUTCOMES ("after Create then Get, the
//     task is there").
//
//   - A MOCK records calls and returns programmed values. It does not
//     really store anything. You assert on INTERACTIONS ("Create was
//     called exactly once, with this argument").
//
// Use a fake when the test cares what happened. Use a mock when the test
// cares that a specific call was (or was not) made.
package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"

	"gotask/internal/domain"
	"gotask/internal/repository"
)

// TaskRepository is a testify mock satisfying repository.TaskRepository.
type TaskRepository struct {
	mock.Mock
}

// compile-time proof this mock satisfies the real interface.
var _ repository.TaskRepository = (*TaskRepository)(nil)

func (m *TaskRepository) Create(ctx context.Context, in domain.NewTaskInput) (domain.Task, error) {
	args := m.Called(ctx, in)
	return args.Get(0).(domain.Task), args.Error(1)
}

func (m *TaskRepository) GetByID(ctx context.Context, id uuid.UUID) (domain.Task, error) {
	args := m.Called(ctx, id)
	return args.Get(0).(domain.Task), args.Error(1)
}

func (m *TaskRepository) List(ctx context.Context, f repository.TaskFilter) ([]domain.Task, error) {
	args := m.Called(ctx, f)
	return args.Get(0).([]domain.Task), args.Error(1)
}

func (m *TaskRepository) Update(ctx context.Context, id uuid.UUID, in repository.UpdateTaskInput) (domain.Task, error) {
	args := m.Called(ctx, id, in)
	return args.Get(0).(domain.Task), args.Error(1)
}

func (m *TaskRepository) Delete(ctx context.Context, id uuid.UUID) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}
